### ISSUE TITLE
error when n_gpus_gen is bigger than 1

### ISSUE THREAD

**Issue by peterzcc** [NVIDIA/vid2vid#62]
Dear Contributors,

Thanks for sharing your code.

I found that when I set --n_gpus_gen > 1, the following error occurs:

`
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCTensorCopy.cu line=102 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "train.py", line 300, in <module>
    train()
  File "train.py", line 107, in train
    fake_B, fake_B_raw, flow, weight, real_A, real_Bp, fake_B_last = modelG(input_A, input_B, inst_A, fake_B_last)            
  File "/home/data/czeng/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/data/czeng/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/data/czeng/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/data/czeng/vid2vid/models/vid2vid_model_G.py", line 130, in forward
    fake_B, fake_B_raw, flow, weight = self.generate_frame_train(netG, real_A_all, fake_B_prev, start_gpu, is_first_frame)        
  File "/home/data/czeng/vid2vid/models/vid2vid_model_G.py", line 176, in generate_frame_train
    fake_B_feat, flow_feat, fake_B_fg_feat, use_raw_only)
  File "/home/data/czeng/vid2vid/models/networks.py", line 195, in forward
    mask = mask.cuda(gpu_id).expand_as(img_raw)            
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/aten/src/THC/THCTensorCopy.cu:102
terminate called after throwing an instance of 'at::Error'
`
However, the following parameter setting wouldn't produce the error:
`
python train.py --gpu_ids 0,1,2,3 --n_gpus_gen 1 --name label2city_256_g1 --label_nc 35 --loadSize 256 --use_instance --fg --n_downsample_G 2 --num_D 1 --max_frames_per_gpu 2 --n_frames_total 2

`
Please help to find the problem. Thanks a lot!

**Comment by tcwang0509** [comment]
What's the exact command you used?

**Comment by peterzcc** [comment]
The command was like the following:
`python train.py --gpu_ids 0,1,2 --n_gpus_gen 2 --name label2city_256_g1 --label_nc 35 --loadSize 128 --use_instance --fg --n_downsample_G 2 --num_D 1 --max_frames_per_gpu 2 --n_frames_total 2`

A new finding is that the program actually gets stuck at this point: https://github.com/howardmumu/vid2vid/blob/13492694c4485cb4bea12ff6bcf52e3243afcefc/models/networks.py#L280

It seems like the Resample2D module works well at the first time. But at the second time the img_prev and flow are on a different GPU, the program just gets stuck forever if I add a line to print the img_warp variable.

**Comment by tcwang0509** [comment]
I ran your command and it works fine. Can you provide more sys info?

**Comment by cientgu** [comment]
i have met the same issue, how did you fix it?

**Comment by peterzcc** [comment]
@cientgu I think this bug happens on specific multi-GPU configurations. Did not find a solution.

**Comment by busning** [comment]
I also tested using 8 gpus, only --n_gpus_gen 1 works, @cientgu did you figure it out?

**Comment by cientgu** [comment]
> I also tested using 8 gpus, only --n_gpus_gen 1 works, @cientgu did you figure it out?

Yes, in models/flownet2_pytorch/networks/resample2d_package/resample2d.py, class Resample2d(Module), add "with torch.cuda.device_of(input1_c):" before return in forward function. This error happened because of the wrong memory allocation.

**Comment by busning** [comment]
@cientgu It works well. Thank you so much!
